"""
05 — Security Compliance Auditor

Simulates an agent that reads cloud resource configuration and security
policies, then audits the infrastructure for compliance violations.

Flow:
  1. Read cloud resource data from JSON (simulates cloud provider API)
  2. Convert resources to Euclid facts
  3. Load compliance policies from .euclid file
  4. Call reason() to find all violations
  5. Format a human-readable compliance report with proof chains
"""
import json
import sys
from pathlib import Path

from euclid_mcp.server import reason
from euclid_mcp.models import ProofNode


def resource_to_facts(r: dict) -> list[str]:
    """Convert a cloud resource JSON object into Euclid facts."""
    rid = r["id"]
    return [
        f'environment({rid}, {r["env"]})',
        f'encrypted({rid}, {str(r["encrypted"]).lower()})',
        f'backup({rid}, {str(r["backup"]).lower()})',
        f'public_access({rid}, {str(r["public"]).lower()})',
    ]


REASON_LABELS = {
    "unencrypted_prod_resource": "unencrypted production resource",
    "missing_backup": "missing automated backup",
    "publicly_exposed": "publicly accessible in production",
}


def flatten_proof(proof: ProofNode | None) -> list[str]:
    """Extract all leaf facts from a proof tree in order."""
    if proof is None:
        return []
    if proof.type == "fact":
        return [str(proof.goal)]
    if proof.type == "rule":
        return flatten_proof(proof.subproof)
    if proof.type == "and":
        result = []
        if proof.left:
            result.extend(flatten_proof(proof.left))
        if proof.right:
            result.extend(flatten_proof(proof.right))
        return result
    return []


def format_report(result, all_resources: list[dict]) -> str:
    """Format the compliance audit output with human-readable proof chains."""
    violated_ids = set()
    for sol in result.solutions:
        rid = sol.substitutions.get("resource", "")
        violated_ids.add(rid)

    compliant = [r for r in all_resources if r["id"] not in violated_ids]
    lines = []
    lines.append("=" * 60)
    lines.append("  COMPLIANCE AUDIT REPORT")
    lines.append("  Generated by Euclid-MCP")
    lines.append("=" * 60)
    lines.append("")
    lines.append(f"  Resources checked: {len(all_resources)}")
    lines.append(f"  Fully compliant:   {len(compliant)}")
    lines.append(f"  Violations found:  {len(result.solutions)}")
    lines.append("")

    for i, sol in enumerate(result.solutions, 1):
        rid = sol.substitutions.get("resource", "?")
        reason_name = sol.substitutions.get("reason", "?")
        label = REASON_LABELS.get(reason_name, reason_name)
        lines.append(f"  {'─' * 56}")
        lines.append(f"  ❌ Violation #{i}: {rid}")
        lines.append(f"     Reason: {label}")
        lines.append("")

        if sol.proof:
            premises = flatten_proof(sol.proof)
            for j, prem in enumerate(premises, 1):
                lines.append(f"     {j}. {prem}")
            lines.append("")
            lines.append(f"     → Rule violated: {reason_name}")

        lines.append("")

    if compliant:
        lines.append(f"  {'─' * 56}")
        lines.append("  ✅ Fully compliant resources:")
        for r in compliant:
            lines.append(f"     ✓ {r['id']}")
        lines.append("")

    lines.append("=" * 60)
    return "\n".join(lines)


def main():
    data_path = Path(__file__).parent / "cloud_resources.json"
    policies_path = Path(__file__).parent / "compliance_policies.euclid"

    if not data_path.exists():
        print(f"ERROR: {data_path} not found")
        sys.exit(1)
    if not policies_path.exists():
        print(f"ERROR: {policies_path} not found")
        sys.exit(1)

    # Step 1: read cloud resources
    with open(data_path) as f:
        all_resources = json.load(f)
    print(f"Read {len(all_resources)} cloud resources from {data_path.name}")

    # Step 2: convert to Euclid facts
    facts = []
    for r in all_resources:
        facts.extend(resource_to_facts(r))
    facts_str = "\n".join(facts)
    print(f"Converted to {len(facts)} Euclid facts")

    # Step 3: load compliance policies
    with open(policies_path) as f:
        policies = f.read()

    # Step 4: combine and run reason()
    knowledge = facts_str + "\n" + policies
    result = reason(knowledge=knowledge, max_solutions=50)
    print(f"Query: {result.query}")
    print(f"Euclid execution: {result.elapsed_ms:.1f} ms")
    print(f"Solutions: {len(result.solutions)}")
    print()

    # Step 5: format human-readable report
    report = format_report(result, all_resources)
    print(report)


if __name__ == "__main__":
    main()
