"""
06 — Loan Eligibility Decision Engine

Simulates an agent that reads applicant data from a CRM export (CSV) and
applies pre-defined lending policies to produce eligibility decisions.

Flow:
  1. Read applicant data from CSV (simulates CRM export)
  2. Convert each applicant to categorized Euclid facts
  3. Load lending policies from .euclid file
  4. Call reason() for overall eligibility
  5. For each declined applicant, check individual conditions
     and produce a detailed breakdown with reason
"""
import csv
import sys
from pathlib import Path

from euclid_mcp.server import reason
from euclid_mcp.models import ProofNode


def categorize_applicant(row: dict) -> list[str]:
    """Convert a CSV row into categorized Euclid facts."""
    name = row["name"].strip().lower()
    age = int(row["age"])
    income = int(row["income"])
    credit = int(row["credit_score"])
    employed = row["employed"].strip().lower() == "true"

    facts = []
    facts.append(f"age({name}, {age})")
    facts.append(f"income({name}, {income})")
    facts.append(f"credit_score({name}, {credit})")

    # Age
    if age >= 18:
        facts.append(f"adult({name})")
    else:
        facts.append(f"minor({name})")

    # Income brackets
    if income > 70000:
        facts.append(f"income_high({name})")
    elif income > 40000:
        facts.append(f"income_medium({name})")
    else:
        facts.append(f"income_low({name})")

    # Credit tiers
    if credit >= 750:
        facts.append(f"credit_excellent({name})")
    elif credit >= 650:
        facts.append(f"credit_good({name})")
    elif credit >= 550:
        facts.append(f"credit_fair({name})")
    else:
        facts.append(f"credit_poor({name})")

    # Employment
    if employed:
        facts.append(f"employed({name})")
    else:
        facts.append(f"unemployed({name})")

    return facts


def flatten_proof(proof: ProofNode | None) -> list[str]:
    """Extract all leaf facts from a proof tree in order."""
    if proof is None:
        return []
    if proof.type == "fact":
        return [str(proof.goal)]
    if proof.type == "rule":
        return flatten_proof(proof.subproof)
    if proof.type == "and":
        result = []
        if proof.left:
            result.extend(flatten_proof(proof.left))
        if proof.right:
            result.extend(flatten_proof(proof.right))
        return result
    return []


def main():
    data_path = Path(__file__).parent / "applicants.csv"
    policies_path = Path(__file__).parent / "loan_policies.euclid"

    if not data_path.exists():
        print(f"ERROR: {data_path} not found")
        sys.exit(1)
    if not policies_path.exists():
        print(f"ERROR: {policies_path} not found")
        sys.exit(1)

    # Step 1: read applicants from CSV
    with open(data_path) as f:
        reader = csv.DictReader(f)
        applicants = list(reader)
    print(f"Read {len(applicants)} applicants from {data_path.name}")

    # Step 2: convert all applicants to Euclid facts
    all_facts = []
    for row in applicants:
        all_facts.extend(categorize_applicant(row))
    facts_str = "\n".join(all_facts)
    print(f"Generated {len(all_facts)} Euclid facts")

    # Step 3: load lending policies
    with open(policies_path) as f:
        policies = f.read()

    knowledge = facts_str + "\n" + policies

    # Step 4: overall eligibility query
    result = reason(knowledge=knowledge, query="eligible($who)", max_solutions=10)
    eligible_names = {
        sol.substitutions.get("who", "").lower()
        for sol in result.solutions
    }

    # Step 5: format report
    lines = []
    lines.append("=" * 60)
    lines.append("  LOAN ELIGIBILITY DECISIONS")
    lines.append("  Generated by Euclid-MCP")
    lines.append(f"  Euclid execution: {result.elapsed_ms:.1f} ms")
    lines.append("=" * 60)
    lines.append("")
    lines.append(f"  Applicants processed: {len(applicants)}")
    lines.append(f"  Approved:             {len(eligible_names)}")
    lines.append(f"  Declined:             {len(applicants) - len(eligible_names)}")
    lines.append("")

    for row in applicants:
        name_raw = row["name"].strip()
        name = name_raw.lower()
        lines.append(f"  {'─' * 56}")
        lines.append(f"  Applicant: {name_raw}")

        if name in eligible_names:
            lines.append("  ✅ DECISION: APPROVED")
            lines.append("")
            # Find and show proof
            for sol in result.solutions:
                if sol.substitutions.get("who", "").lower() == name:
                    premises = flatten_proof(sol.proof)
                    for j, prem in enumerate(premises, 1):
                        lines.append(f"     {j}. {prem}")
                    break
            lines.append("  → All conditions met")
        else:
            lines.append("  ❌ DECISION: DECLINED")
            lines.append("")
            # Check each sub-condition
            checks = [
                ("adult", "Age check (requires 18+)"),
                ("income_high", "Income: high"),
                ("income_medium", "Income: medium"),
                ("credit_excellent", "Credit: excellent (750+)"),
                ("credit_good", "Credit: good (650-749)"),
                ("credit_fair", "Credit: fair (550-649)"),
                ("employed", "Employment: employed"),
            ]
            any_income = False
            any_credit = False
            for pred, desc in checks:
                check = reason(
                    knowledge=knowledge, query=f"{pred}({name})"
                )
                if check.solutions:
                    mark = "✓"
                    if pred in ("income_high", "income_medium"):
                        any_income = True
                    if pred in ("credit_excellent", "credit_good", "credit_fair"):
                        any_credit = True
                else:
                    mark = "✗"
                lines.append(f"     {mark} {desc}")

            # Show raw data
            age = row["age"]
            income = row["income"]
            credit = row["credit_score"]
            employed = row["employed"]
            lines.append("")
            lines.append(f"     Raw data: age={age}, income={income}, "
                         f"credit_score={credit}, employed={employed}")
            lines.append("")

            # Determine primary reason
            if not any_credit:
                credit_val = int(row["credit_score"])
                lines.append(f"     → Primary reason: insufficient credit score "
                             f"({credit_val}, needs 650+)")
            elif row["employed"].strip().lower() != "true":
                lines.append("     → Primary reason: not employed")
            elif not any_income:
                lines.append("     → Primary reason: insufficient income")
            else:
                lines.append("     → Primary reason: does not meet any eligibility path")

        lines.append("")

    lines.append("=" * 60)
    lines.append("")
    lines.append("  ALTERNATIVE PATHS")
    # Check who qualifies for conditional approval
    cond_result = reason(knowledge=knowledge, query="conditional($who)", max_solutions=10)
    if cond_result.solutions:
        for sol in cond_result.solutions:
            cname = sol.substitutions.get("who", "")
            lines.append(f"  • {cname}: eligible for conditional approval "
                         f"(approved if employment obtained)")
    else:
        lines.append("  (none)")

    lines.append("")
    lines.append("=" * 60)
    print("\n".join(lines))


if __name__ == "__main__":
    main()
