import re

from .language import (
    VAR_NAME_RE,
    _extract_strings,
    _restore_strings,
    strip_query_prefix,
)
from .models import KB

META_INTERPRETER = """
% meta-interpreter: prove(+Goal, +MaxDepth, -ProofTree)
% Built-in arithmetic/comparison operators
is_arith_goal(Goal) :-
    Goal =.. [Op, _, _],
    member(Op, [>, >=, =<, <, =:=, =\\=, is]).

prove(true, _, true) :- !.
% false literal: always fails, never reaches clause/2 (clause/2 over the
% built-in false/fail raises permission_error in SWI-Prolog 10).
prove(false, _, _) :- !, fail.
prove((A, B), D, and(PA, PB)) :- !,
    prove(A, D, PA),
    prove(B, D, PB).
prove(Goal, _, true) :-
    is_arith_goal(Goal), !,
    Goal.
prove(\\+ Goal, D, neg(Goal, negated)) :- !,
    \\+ prove(Goal, D, _).
% Built-in guard: user clauses can never exist for a built-in predicate
% (SWI-Prolog forbids asserting them), so any built-in body goal simply
% fails cleanly instead of raising permission_error inside clause/2.
% This mirrors the native engine, where unknown predicates fail cleanly.
prove(Goal, _, fact(Goal)) :-
    \\+ predicate_property(Goal, built_in),
    clause(Goal, true).
prove(Goal, D, rule(Goal, Rest, BodyProof, Id)) :-
    \\+ predicate_property(Goal, built_in),
    D > 0,
    D1 is D - 1,
    clause(Goal, Body),
    Body \\= true,
    decompose_rule_id(Body, Rest, Id),
    prove(Rest, D1, BodyProof).

decompose_rule_id((euclid_rule_id(Id), Rest), Rest, Id) :- !.
decompose_rule_id(euclid_rule_id(Id), true, Id) :- !.
decompose_rule_id(Body, Body, null).
"""

PROOF_TO_JSON = """
proof_to_json(fact(G), _{type:"fact", goal:S}) :-
    term_string(G, S), !.
proof_to_json(rule(G, B, P, Id), _{type:"rule", goal:SG, body:SB, subproof:SP, rule_id:SId}) :-
    Id \\= null,
    term_string(G, SG),
    term_string(B, SB),
    proof_to_json(P, SP),
    atom_string(Id, SId), !.
proof_to_json(rule(G, B, P, _), _{type:"rule", goal:SG, body:SB, subproof:SP}) :-
    term_string(G, SG),
    term_string(B, SB),
    proof_to_json(P, SP), !.
proof_to_json(and(P1, P2), _{type:"and", left:J1, right:J2}) :-
    proof_to_json(P1, J1),
    proof_to_json(P2, J2), !.
proof_to_json(neg(G, _), _{type:"neg", goal:S, result:"negated"}) :-
    term_string(G, S), !.
proof_to_json(true, _{type:"true"}) :- !.

% JSON-safe conversion for solution bindings: unbound variables become
% JSON null (so non-range-restricted rules keep their solutions, like the
% native engine), atoms become strings, numbers pass through unchanged,
% any other term (compound, list) is rendered with term_string/2.
euclid_json_value(V, @(null)) :- var(V), !.
euclid_json_value(V, S) :- atom(V), !, atom_string(V, S).
euclid_json_value(V, V) :- number(V), !.
euclid_json_value(V, S) :- term_string(V, S).
"""


def to_prolog(kb: KB, max_depth: int = 30, max_solutions: int = 1000) -> str:
    parts = []

    parts.append("% generated by Euclid-MCP translator")
    parts.append("")
    parts.append(":- catch(use_module(library(http/json)), _, true).")
    parts.append(":- use_module(library(lists)).")
    parts.append("")

    all_statements: list[str] = []
    pred_sigs: set[str] = set()

    for f in kb.facts:
        s = _translate_statement(f)
        all_statements.append(s)
        sig = _extract_pred_sig(f)
        if sig:
            pred_sigs.add(sig)

    for i, r in enumerate(kb.rules):
        s = _translate_rule(r, kb.rule_ids.get(i))
        all_statements.append(s)
        head = re.split(r"\s+[Ii][Ff]\s+", r, maxsplit=1)[0].strip()
        sig = _extract_pred_sig(head)
        if sig:
            pred_sigs.add(sig)

    all_statements.sort(
        key=lambda x: (x.split("(")[0].split(" ")[0], x)
    )

    if pred_sigs:
        decls = ", ".join(
            sorted(pred_sigs, key=lambda x: (x.split("/")[0], int(x.split("/")[1])))
        )
        parts.append(f":- dynamic {decls}.")
        parts.append("")

    parts.extend(all_statements)
    parts.append("")

    parts.append(META_INTERPRETER.strip())
    parts.append("")
    parts.append(PROOF_TO_JSON.strip())
    parts.append("")

    output_pred = _generate_output(kb, max_depth, max_solutions)
    parts.extend(output_pred)
    parts.append("")

    parts.append(":- output, halt.")
    parts.append("")

    return "\n".join(parts) + "\n"


def _translate_vars(s: str) -> str:
    """Mask $vars as ``__VAR_name__`` placeholders, preserving quoted strings."""
    cleaned, strings = _extract_strings(s)
    masked = _mask_vars(cleaned)
    for i, str_literal in enumerate(strings):
        masked = masked.replace(f"__STR_{i}__", str_literal)
    return masked


def _translate_operators(s: str) -> str:
    """Translate Euclid-IR operators to Prolog operators.

    ==  -> =:=   (arithmetic equality)
    !=  -> =\\=  (arithmetic inequality)
    <=  -> =<    (less or equal, Prolog style)

    Quoted strings are protected so operators inside them stay untouched.
    """
    cleaned, strings = _extract_strings(s)
    cleaned = re.sub(r"==", "=:= ", cleaned)
    cleaned = re.sub(r"!=", "=\\= ", cleaned)
    cleaned = re.sub(r"<=", "=< ", cleaned)
    return _restore_strings(cleaned, strings)


def _translate_statement(fact: str) -> str:
    return _quote_goal(_translate_operators(_translate_vars(fact.strip().rstrip(".")))) + "."


def _prolog_escape_str(s: str) -> str:
    """Escape a string for safe use as a Prolog single-quoted atom."""
    return "'" + s.replace("\\", "\\\\").replace("'", "''") + "'"


_PLACEHOLDER_RE = re.compile(r"^__STR_\d+__$")

_VAR_MASK_RE = re.compile(r"__VAR_(.+?)__")


def _mask_vars(s: str) -> str:
    """Replace ``$vars`` with ``__VAR_name__`` placeholders.

    Masking instead of translating directly to capitalized variables keeps
    the later atom-quoting pass from ever seeing variables: a naive quoter
    would wrap a non-ASCII variable like ``$кто`` into the atom ``'Кто'``
    (uppercase-initial looks unsafe), which then never unifies.
    """
    return VAR_NAME_RE.sub(lambda m: f"__VAR_{m.group(1)}__", s)


def _unmask_vars(s: str) -> str:
    """Replace ``__VAR_name__`` placeholders with Prolog variables."""
    return _VAR_MASK_RE.sub(lambda m: m.group(1).capitalize(), s)


def _literal_to_prolog(literal: str) -> str:
    """Convert an IR quoted literal (``"..."`` or ``'...'``) to a Prolog atom.

    Euclid-IR strings are opaque atomic values: the native engine binds
    their unquoted content, while SWI double-quoted syntax produces *string*
    terms that serialize with their quotes via ``term_string/3`` — a silent
    backend divergence. Re-emitting as a single-quoted atom keeps both
    backends byte-identical.
    """
    if len(literal) >= 2 and literal[0] == literal[-1] and literal[0] in "\"'":
        # Unescape exactly like ir_parser._read_string: \x -> x.
        out: list[str] = []
        body = literal[1:-1]
        i = 0
        while i < len(body):
            ch = body[i]
            if ch == "\\" and i + 1 < len(body):
                out.append(body[i + 1])
                i += 2
            else:
                out.append(ch)
                i += 1
        return _prolog_escape_str("".join(out))
    return literal


def _quote_atom(name: str) -> str:
    """Single-quote a Prolog atom whose first char would be misread.

    An atom is safe unquoted when it starts with an ASCII lowercase letter
    ([a-z]). Anything else gets single-quoted: SWI-Prolog would otherwise
    parse an uppercase initial (e.g. Cyrillic 'Бог') as a variable, and a
    CJK/caseless name (e.g. '父') gets quoted for clarity. Quoted and
    unquoted atoms are identical in SWI-Prolog, so this is always safe.
    """
    if name and "a" <= name[0] <= "z":
        return name
    return _prolog_escape_str(name)


def _quote_term(term: str) -> str:
    """Recursively quote unsafe atoms in a Prolog term string.

    Leaves $var-derived variables (ASCII uppercase first char), the
    anonymous `_`, numbers, and quoted-string placeholders untouched.
    """
    term = term.strip()
    if not term:
        return term
    if _PLACEHOLDER_RE.match(term):
        return term
    if term.startswith("__VAR_"):
        return term  # masked variable token
    if term.startswith("(") and term.endswith(")"):
        inner = term[1:-1]
        args = _split_args(inner)
        return "(" + ", ".join(_quote_term(a) for a in args) + ")"
    open_idx = term.find("(")
    if open_idx >= 0 and term.endswith(")"):
        name = term[:open_idx].strip()
        inner = term[open_idx + 1 : -1]
        args = _split_args(inner)
        return f"{_quote_atom(name)}({', '.join(_quote_term(a) for a in args)})"
    # atomic token
    if term == "_":
        return term
    if term.startswith("__VAR_") or "__STR_" in term:
        # Masked variable / string placeholder inside an operator expression
        # (e.g. "__VAR_days__ > 90"): leave the whole expression untouched.
        return term
    if term[0].isascii() and term[0].isupper():
        return term  # translated $var -> Variable
    try:
        float(term)
        return term
    except ValueError:
        pass
    return _quote_atom(term)


def _quote_goal(pl_goal: str) -> str:
    """Quote unsafe atoms in a single Prolog goal (protects string literals)."""
    cleaned, strings = _extract_strings(pl_goal)
    result = _quote_term(cleaned)
    for i, s in enumerate(strings):
        result = result.replace(f"__STR_{i}__", _literal_to_prolog(s))
    return _unmask_vars(result)


def _quote_body(pl_body: str) -> str:
    """Quote unsafe atoms in a Prolog body; handle `\\+ ` and paren-wraps."""
    cleaned, strings = _extract_strings(pl_body)
    goals = _split_args(cleaned)
    quoted = []
    for g in goals:
        g = g.strip()
        if g.startswith("\\+ "):
            quoted.append("\\+ " + _quote_term(g[3:].strip()))
        else:
            quoted.append(_quote_term(g))
    result = ", ".join(quoted)
    for i, s in enumerate(strings):
        result = result.replace(f"__STR_{i}__", _literal_to_prolog(s))
    return _unmask_vars(result)


def _split_args(s: str) -> list[str]:
    """Split a comma-separated string at top level, respecting parentheses."""
    parts: list[str] = []
    depth = 0
    cur: list[str] = []
    for ch in s:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append("".join(cur).strip())
            cur = []
        else:
            cur.append(ch)
    if cur:
        parts.append("".join(cur).strip())
    return parts


def _translate_rule(rule: str, rule_id: str | None = None) -> str:
    head, body = re.split(r"\s+[Ii][Ff]\s+", rule, maxsplit=1)
    head_pl = _quote_goal(_translate_vars(head.strip()))
    body = re.sub(r"\s+[Aa][Nn][Dd]\s+", ", ", body.strip())
    body_pl = _translate_vars(body)
    # Convert NOT to Prolog negation
    body_pl = re.sub(r"\b[Nn][Oo][Tt]\s+", "\\+ ", body_pl)
    body_pl = _translate_operators(body_pl)
    body_pl = _quote_body(body_pl)
    if rule_id:
        # Prepend the rule ID marker so the meta-interpreter can attach it
        # to the proof tree (audit trail: "this decision derives from rule X").
        body_pl = f"euclid_rule_id({_prolog_escape_str(rule_id)}), {body_pl}"
    return f"{head_pl} :- {body_pl}."


def _extract_pred_sig(term: str) -> str | None:
    term = term.strip()
    m = re.match(r"(\w+)\s*\((.*)\)\s*$", term)
    if not m:
        # Bare zero-arity statement (e.g. "rainy" or a "t IF true" head).
        # Without a signature the predicate is never declared dynamic nor
        # registered in the engine workspace, so its clause survives
        # clear_workspace and duplicates on every subsequent load.
        if re.fullmatch(r"\w+", term):
            return f"{_quote_atom(term)}/0"
        return None
    name = m.group(1)
    args_str = m.group(2).strip()
    if not args_str:
        return f"{_quote_atom(name)}/0"
    depth = 0
    arity = 1
    for c in args_str:
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
        elif c == "," and depth == 0:
            arity += 1
    return f"{_quote_atom(name)}/{arity}"


# Predicates provided to the persistent engine along with every KB load
# (meta-interpreter + proof-tree serializer). They are declared dynamic and
# asserted like ordinary clauses; the engine's stats exclude them.
_ENGINE_PREDICATES = frozenset(
    [
        "prove/3",
        "is_arith_goal/1",
        "decompose_rule_id/3",
        "proof_to_json/2",
        "euclid_rule_id/1",
    ]
)


def _translate_query(query: str) -> tuple[str, list[str]]:
    """Translate a Euclid-IR query into (prolog goal, ordered var names)."""
    query = strip_query_prefix(query)
    query_body = re.sub(r"\s+[Aa][Nn][Dd]\s+", ", ", query.strip().rstrip("."))
    # Wrap in parentheses if it's a conjunction (contains commas at top level)
    if ", " in query_body:
        query_body = f"({query_body})"
    query_pl = _quote_body(_translate_operators(_translate_vars(query_body)))
    # Deduplicate variable names while preserving order
    seen: set[str] = set()
    var_names: list[str] = []
    for vn in VAR_NAME_RE.findall(query):
        if vn not in seen:
            seen.add(vn)
            var_names.append(vn)
    return query_pl, var_names


def kb_to_decls_clauses(kb: KB) -> tuple[list[str], list[str]]:
    """Split a KB into (dynamic declarations, clause texts) for the engine.

    The clauses carry the user facts/rules plus the meta-interpreter and the
    proof-tree serializer; declarations cover both user predicates and the
    engine helpers. Order of the returned list matches ``to_prolog`` for the
    user statements, so solution ordering is identical.
    """
    decls: set[str] = set()
    clauses: list[str] = []

    for f in kb.facts:
        clauses.append(_translate_statement(f))
        sig = _extract_pred_sig(f)
        if sig:
            decls.add(sig)

    for i, r in enumerate(kb.rules):
        clauses.append(_translate_rule(r, kb.rule_ids.get(i)))
        head = re.split(r"\s+[Ii][Ff]\s+", r, maxsplit=1)[0].strip()
        sig = _extract_pred_sig(head)
        if sig:
            decls.add(sig)

    clauses.sort(key=lambda x: (x.split("(")[0].split(" ")[0], x))

    decls.update(_ENGINE_PREDICATES)
    clauses.extend([META_INTERPRETER.strip(), PROOF_TO_JSON.strip()])

    return (
        sorted(decls, key=lambda x: (x.split("/")[0], int(x.split("/")[1]))),
        clauses,
    )


def build_query_snippet(
    query: str, max_depth: int = 30, max_solutions: int = 1000
) -> str:
    """Build the Prolog snippet for the engine's query command.

    The snippet streams a JSON array of result dicts
    (``{'solution': {...}, 'proof': {...}}``) to ``current_output`` via
    ``forall/2`` + ``json_write/3``; the engine captures it and replies
    with ``{"status": "ok", "solutions": "<json array>"}``. Streaming
    keeps large result sets fast and low-memory.

    The enumeration is capped at ``max_solutions`` on the Prolog side
    (via an ``nb_setval/2`` counter inside the ``forall/2`` generator) so an
    explosive query stops producing once the requested count is reached,
    instead of buffering every solution up to the engine timeout.
    """
    query_pl, var_names = _translate_query(query)
    var_entries = [f"'{vn}': J{vn.capitalize()}" for vn in var_names]
    subs_dict = ", ".join(var_entries)
    if var_entries:
        result_line = "Result = _{{'solution': _{{{s}}}, 'proof': JProof}}".format(
            s=subs_dict
        )
    else:
        result_line = "Result = _{'solution': _{}, 'proof': JProof}"

    # Convert every query variable to a JSON-safe value before building the
    # result dict: json_write/3 raises type_error(json_term, ...) on compound
    # bindings (e.g. structured terms returned by nested-compound KBs).
    conv_lines = [
        f"euclid_json_value({vn.capitalize()}, J{vn.capitalize()}),"
        for vn in var_names
    ]

    return "\n".join(
        [
            "retractall(euclid_array_first), assertz(euclid_array_first),",
            f"MaxDepth = {max_depth},",
            f"MaxSolutions = {max_solutions},",
            f"Query = {query_pl},",
            "nb_setval(euclid_solution_count, 0),",
            "write('['),",
            "forall(",
            "    ( prove(Query, MaxDepth, Proof),",
            "      nb_getval(euclid_solution_count, C0),",
            "      C0 < MaxSolutions,",
            "      C1 is C0 + 1,",
            "      nb_setval(euclid_solution_count, C1) ),",
            "    ( proof_to_json(Proof, JProof),",
            *conv_lines,
            "      array_separator,",
            f"      {result_line},",
            "      json_write(current_output, Result, [width(0)])",
            "    )",
            "),",
            "write(']')",
        ]
    )


def _generate_output(kb: KB, max_depth: int, max_solutions: int) -> list[str]:
    query = kb.query
    if not query:
        return ["output :- true."]

    query_pl, var_names = _translate_query(query)

    var_entries = []
    conv_entries = []
    for vn in var_names:
        prolog_var = vn.capitalize()
        json_var = f"J{prolog_var}"
        var_entries.append(f"'{vn}': {json_var}")
        conv_entries.append(f"euclid_json_value({prolog_var}, {json_var}),")
    subs_dict = ", ".join(var_entries)

    lines = [
        "output :-",
        f"    MaxDepth = {max_depth},",
        f"    MaxSolutions = {max_solutions},",
        f"    Query = {query_pl},",
        "    nb_setval(euclid_solution_count, 0),",
        "    forall(",
        "        ( prove(Query, MaxDepth, Proof),",
        "          nb_getval(euclid_solution_count, C0),",
        "          C0 < MaxSolutions,",
        "          C1 is C0 + 1,",
        "          nb_setval(euclid_solution_count, C1) ),",
        "        ( proof_to_json(Proof, JProof),",
        *conv_entries,
    ]
    if var_entries:
        line = "          Result = _{{'solution': _{{{s}}}, 'proof': JProof}},".format(
            s=subs_dict
        )
        lines.append(line)
    else:
        lines.append("          Result = _{'solution': _{}, 'proof': JProof},")

    lines.extend([
        "          catch(json_write(current_output, Result, [width(0)]), _, true),",
        "          nl, flush_output",
        "        )",
        "    ).",
    ])
    return lines
