import re

from .language import _extract_strings
from .models import KB

META_INTERPRETER = """
% meta-interpreter: prove(+Goal, +MaxDepth, -ProofTree)
% Built-in arithmetic/comparison operators
is_arith_goal(Goal) :-
    Goal =.. [Op, _, _],
    member(Op, [>, >=, =<, <, =:=, =\\=, is]).

prove(true, _, true) :- !.
prove((A, B), D, and(PA, PB)) :- !,
    prove(A, D, PA),
    prove(B, D, PB).
prove(Goal, _, true) :-
    is_arith_goal(Goal), !,
    Goal.
prove(\\+ Goal, D, neg(Goal, negated)) :- !,
    \\+ prove(Goal, D, _).
prove(Goal, _, fact(Goal)) :-
    clause(Goal, true).
prove(Goal, D, rule(Goal, Body, BodyProof)) :-
    D > 0,
    D1 is D - 1,
    clause(Goal, Body),
    Body \\= true,
    prove(Body, D1, BodyProof).
"""

PROOF_TO_JSON = """
proof_to_json(fact(G), _{type:"fact", goal:S}) :-
    term_string(G, S), !.
proof_to_json(rule(G, B, P), _{type:"rule", goal:SG, body:SB, subproof:SP}) :-
    term_string(G, SG),
    term_string(B, SB),
    proof_to_json(P, SP), !.
proof_to_json(and(P1, P2), _{type:"and", left:J1, right:J2}) :-
    proof_to_json(P1, J1),
    proof_to_json(P2, J2), !.
proof_to_json(neg(G, _), _{type:"neg", goal:S, result:"negated"}) :-
    term_string(G, S), !.
proof_to_json(true, _{type:"true"}) :- !.
"""


def to_prolog(kb: KB, max_depth: int = 30, max_solutions: int = 1000) -> str:
    parts = []

    parts.append("% generated by Euclid-MCP translator")
    parts.append("")
    parts.append(":- catch(use_module(library(http/json)), _, true).")
    parts.append(":- use_module(library(lists)).")
    parts.append("")

    all_statements: list[str] = []
    pred_sigs: set[str] = set()

    for f in kb.facts:
        s = _translate_statement(f)
        all_statements.append(s)
        sig = _extract_pred_sig(f)
        if sig:
            pred_sigs.add(sig)

    for r in kb.rules:
        s = _translate_rule(r)
        all_statements.append(s)
        head = re.split(r"\s+[Ii][Ff]\s+", r, maxsplit=1)[0].strip()
        sig = _extract_pred_sig(head)
        if sig:
            pred_sigs.add(sig)

    all_statements.sort(
        key=lambda x: (x.split("(")[0].split(" ")[0], x)
    )

    if pred_sigs:
        decls = ", ".join(
            sorted(pred_sigs, key=lambda x: (x.split("/")[0], int(x.split("/")[1])))
        )
        parts.append(f":- dynamic {decls}.")
        parts.append("")

    parts.extend(all_statements)
    parts.append("")

    parts.append(META_INTERPRETER.strip())
    parts.append("")
    parts.append(PROOF_TO_JSON.strip())
    parts.append("")

    output_pred = _generate_output(kb, max_depth, max_solutions)
    parts.extend(output_pred)
    parts.append("")

    parts.append(":- output, halt.")
    parts.append("")

    return "\n".join(parts) + "\n"


def _translate_vars(s: str) -> str:
    """Translate $vars to Prolog vars, preserving quoted strings."""
    cleaned, strings = _extract_strings(s)
    result = re.sub(
        r"\$([a-z][a-zA-Z0-9_]*)", lambda m: m.group(1).capitalize(), cleaned
    )
    for i, str_literal in enumerate(strings):
        result = result.replace(f"__STR_{i}__", str_literal)
    return result


def _translate_operators(s: str) -> str:
    """Translate Euclid-IR operators to Prolog operators.

    != -> =\\=   (arithmetic inequality)
    <=  -> =<    (less or equal, Prolog style)
    """
    s = re.sub(r"!=", "=\\= ", s)
    s = re.sub(r"<=", "=< ", s)
    return s


def _translate_statement(fact: str) -> str:
    return _translate_operators(_translate_vars(fact.strip().rstrip("."))) + "."


def _translate_rule(rule: str) -> str:
    head, body = re.split(r"\s+[Ii][Ff]\s+", rule, maxsplit=1)
    head_pl = _translate_vars(head.strip())
    body = re.sub(r"\s+[Aa][Nn][Dd]\s+", ", ", body.strip())
    body_pl = _translate_vars(body)
    # Convert NOT to Prolog negation
    body_pl = re.sub(r"\b[Nn][Oo][Tt]\s+", "\\+ ", body_pl)
    body_pl = _translate_operators(body_pl)
    return f"{head_pl} :- {body_pl}."


def _extract_pred_sig(term: str) -> str | None:
    m = re.match(r"(\w+)\s*\((.*)\)\s*$", term.strip())
    if not m:
        return None
    name = m.group(1)
    args_str = m.group(2).strip()
    if not args_str:
        return f"{name}/0"
    depth = 0
    arity = 1
    for c in args_str:
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
        elif c == "," and depth == 0:
            arity += 1
    return f"{name}/{arity}"


def _generate_output(kb: KB, max_depth: int, max_solutions: int) -> list[str]:
    query = kb.query
    if not query:
        return ["output :- true."]

    # Convert AND to Prolog conjunction before translating vars
    query_body = re.sub(r"\s+[Aa][Nn][Dd]\s+", ", ", query.strip().rstrip("."))
    # Wrap in parentheses if it's a conjunction (contains commas at top level)
    if ", " in query_body:
        query_body = f"({query_body})"
    query_pl = _translate_vars(query_body)
    # Deduplicate variable names while preserving order
    seen = set()
    var_names = []
    for vn in re.findall(r"\$([a-z][a-zA-Z0-9_]*)", query):
        if vn not in seen:
            seen.add(vn)
            var_names.append(vn)

    var_entries = []
    for vn in var_names:
        prolog_var = vn.capitalize()
        var_entries.append(f"'{vn}': {prolog_var}")
    subs_dict = ", ".join(var_entries)

    lines = [
        "output :-",
        f"    MaxDepth = {max_depth},",
        f"    Query = {query_pl},",
        "    forall(",
        "        prove(Query, MaxDepth, Proof),",
        "        ( proof_to_json(Proof, JProof),",
    ]
    if var_entries:
        line = "          Result = _{{'solution': _{{{s}}}, 'proof': JProof}},".format(
            s=subs_dict
        )
        lines.append(line)
    else:
        lines.append("          Result = _{'solution': _{}, 'proof': JProof},")

    lines.extend([
        "          catch(json_write(current_output, Result, [width(0)]), _, true),",
        "          nl, flush_output",
        "        )",
        "    ).",
    ])
    return lines
